# Generated by Django 6.0.4 on 2026-04-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banco_pessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('curso', models.CharField(max_length=100)),
                ('periodo', models.IntegerField(default=0)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('github', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('url_imagem', models.URLField()),
            ],
        ),
    ]
