# Generated by Django 6.0.4 on 2026-04-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco_pessoal',
            name='github',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='banco_pessoal',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='banco_pessoal',
            name='url_imagem',
            field=models.URLField(blank=True),
        ),
    ]
