# Generated by Django 6.0.4 on 2026-04-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_banco_pessoal_github_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='banco_pessoal',
            new_name='BancoPessoal',
        ),
    ]
