# Generated by Django 6.0.4 on 2026-04-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='link_github',
            field=models.URLField(blank=True),
        ),
    ]
