# Generated by Django 6.0.4 on 2026-04-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_projeto_link_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='certificado',
        ),
        migrations.AddField(
            model_name='certificado',
            name='descricao',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tipo',
            field=models.CharField(choices=[('Pessoal', 'Pessoal'), ('Disciplina', 'Disciplina')], max_length=50),
        ),
    ]
